services:
  - type: web
    name: cbt-learning-platform
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: starter
    healthCheckPath: /api/health
    numInstances: 1
    region: oregon
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: cbt-platform-db
          property: connectionString
    envVars:
      - key: ALOC_ACCESS_TOKEN
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

databases:
  - name: cbt-platform-db
    databaseName: cbt_platform
    user: cbt_user
    plan: starter