import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Key, MessageCircle, CheckCircle, Star, Zap, BookOpen, Trophy, Globe, Calculator } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';

interface ActivateProps {
  user: any;
  onActivated: () => void;
  onBack: () => void;
}

export default function Activate({ user, onActivated, onBack }: ActivateProps) {
  const [activationCode, setActivationCode] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleActivation = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!activationCode) {
      toast({
        title: "Missing Code",
        description: "Please enter the activation code",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    try {
      console.log('Attempting activation with:', { userId: user.id, activationCode: activationCode.trim() });
      
      const response = await fetch('/api/auth/activate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userId: user.id,
          activationCode: activationCode.trim(),
        }),
      });
      
      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.message || 'Activation failed');
      }
      
      onActivated();
      
      toast({
        title: "Account Activated!",
        description: "You now have access to all premium features",
      });
    } catch (error: any) {
      console.error('Activation error:', error);
      toast({
        title: "Activation Failed",
        description: error.message || "Invalid activation code",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const whatsappMessage = encodeURIComponent(
    `Hello! I would like to purchase an activation code for UI POST UTME app.\n\nMy details:\n- Name: ${user.firstName} ${user.lastName}\n- Email: ${user.email}\n- Nickname: ${user.nickname}\n\nPlease provide me with an activation code. Thank you!`
  );

  const premiumFeatures = [
    {
      icon: <Zap className="h-6 w-6" />,
      title: "Unlimited Practice Tests",
      description: "Access to all subjects with unlimited attempts"
    },
    {
      icon: <BookOpen className="h-6 w-6" />,
      title: "AI-Powered Study Plans",
      description: "Personalized study plans generated by Gemini, GPT-4 & Grok"
    },
    {
      icon: <Calculator className="h-6 w-6" />,
      title: "Scientific Calculator",
      description: "Advanced calculator for Mathematics and Physics"
    },
    {
      icon: <Trophy className="h-6 w-6" />,
      title: "Detailed Analytics",
      description: "Track your progress with comprehensive performance insights"
    },
    {
      icon: <Globe className="h-6 w-6" />,
      title: "Wikipedia Integration",
      description: "Research any topic with integrated Wikipedia search"
    },
    {
      icon: <Star className="h-6 w-6" />,
      title: "Priority Support",
      description: "Get priority customer support and feature requests"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-indigo-900 p-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-8">
          <div className="w-20 h-20 bg-gradient-to-r from-purple-500 to-blue-500 rounded-3xl mx-auto mb-6 flex items-center justify-center">
            <Key className="h-10 w-10 text-white" />
          </div>
          <h1 className="text-4xl font-bold text-white mb-4">Activate Premium</h1>
          <p className="text-purple-200 text-lg">Unlock all features and excel in your POST UTME</p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          {/* Activation Form */}
          <Card className="bg-white/10 backdrop-blur-lg border-white/20 shadow-2xl">
            <CardHeader>
              <CardTitle className="text-2xl font-bold text-white text-center">
                Enter Activation Code
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {/* WhatsApp Contact */}
              <div className="bg-green-500/20 border border-green-500/30 rounded-lg p-4">
                <div className="flex items-center mb-3">
                  <MessageCircle className="h-6 w-6 text-green-400 mr-2" />
                  <h3 className="font-semibold text-white">Get Activation Code</h3>
                </div>
                <p className="text-green-100 text-sm mb-4">
                  Contact us on WhatsApp to purchase your activation code
                </p>
                <div className="bg-green-600/20 rounded-lg p-3 mb-4">
                  <p className="text-green-100 text-sm font-medium">Contact Numbers:</p>
                  <p className="text-green-200 text-xs">+234 803 989 6597</p>
                  <p className="text-green-200 text-xs">+234 814 880 4813</p>
                  <p className="text-green-200 text-xs">+234 707 566 3318</p>
                </div>
                <a
                  href={`https://wa.me/2348039896597?text=${whatsappMessage}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center w-full justify-center bg-green-500 hover:bg-green-600 text-white font-semibold py-3 px-4 rounded-lg transition-colors"
                >
                  <MessageCircle className="h-5 w-5 mr-2" />
                  Message on WhatsApp
                </a>
              </div>

              {/* Activation Form */}
              <form onSubmit={handleActivation} className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="activationCode" className="text-white">
                    Activation Code
                  </Label>
                  <div className="relative">
                    <Key className="absolute left-3 top-1/2 transform -translate-y-1/2 h-5 w-5 text-purple-300" />
                    <Input
                      id="activationCode"
                      type="text"
                      placeholder="Enter your activation code"
                      value={activationCode}
                      onChange={(e) => setActivationCode(e.target.value)}
                      className="pl-10 bg-white/20 border-white/30 text-white placeholder:text-purple-200 focus:border-purple-400 focus:ring-purple-400"
                      required
                    />
                  </div>
                  <p className="text-sm text-purple-200">
                    Enter the 7-digit activation code you received via WhatsApp
                  </p>
                </div>

                <Button
                  type="submit"
                  disabled={isLoading}
                  className="w-full bg-gradient-to-r from-purple-500 to-blue-500 hover:from-purple-600 hover:to-blue-600 text-white font-semibold py-3 transition-all duration-200 active:scale-95"
                >
                  {isLoading ? (
                    <div className="flex items-center justify-center">
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                      Activating...
                    </div>
                  ) : (
                    <div className="flex items-center justify-center">
                      <CheckCircle className="h-5 w-5 mr-2" />
                      Activate Premium
                    </div>
                  )}
                </Button>
              </form>

              <Button
                onClick={onBack}
                variant="ghost"
                className="w-full text-purple-300 hover:text-white hover:bg-white/10"
              >
                ← Back to Dashboard
              </Button>
            </CardContent>
          </Card>

          {/* Premium Features */}
          <Card className="bg-white/10 backdrop-blur-lg border-white/20 shadow-2xl">
            <CardHeader>
              <CardTitle className="text-2xl font-bold text-white text-center">
                Premium Features
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {premiumFeatures.map((feature, index) => (
                <div
                  key={index}
                  className="flex items-start space-x-4 p-4 rounded-lg bg-white/10 backdrop-blur-sm"
                >
                  <div className="flex-shrink-0 p-2 bg-gradient-to-r from-purple-500 to-blue-500 rounded-lg">
                    {feature.icon}
                  </div>
                  <div className="flex-1">
                    <h4 className="font-semibold text-white mb-1">{feature.title}</h4>
                    <p className="text-purple-200 text-sm">{feature.description}</p>
                  </div>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>

        {/* Instructions */}
        <Card className="bg-white/10 backdrop-blur-lg border-white/20 shadow-2xl mt-8">
          <CardContent className="p-6">
            <h3 className="text-xl font-semibold text-white mb-4 text-center">
              How to Get Your Activation Code
            </h3>
            <div className="grid md:grid-cols-3 gap-6">
              <div className="text-center">
                <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full mx-auto mb-3 flex items-center justify-center text-white font-bold text-lg">
                  1
                </div>
                <h4 className="font-semibold text-white mb-2">Contact WhatsApp</h4>
                <p className="text-purple-200 text-sm">
                  Click the WhatsApp button to send us a message
                </p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full mx-auto mb-3 flex items-center justify-center text-white font-bold text-lg">
                  2
                </div>
                <h4 className="font-semibold text-white mb-2">Make Payment</h4>
                <p className="text-purple-200 text-sm">
                  Follow the payment instructions we provide
                </p>
              </div>
              <div className="text-center">
                <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-blue-500 rounded-full mx-auto mb-3 flex items-center justify-center text-white font-bold text-lg">
                  3
                </div>
                <h4 className="font-semibold text-white mb-2">Get Code</h4>
                <p className="text-purple-200 text-sm">
                  Receive your 7-digit activation code and enter it above
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}